version: '2.1'

services:
  mailserver:
    image: analogic/poste.io
    container_name: mailserver
    environment:
      - HTTPS=OFF
    ports:
      - "25:25"
      - "110:110"
      - "143:143"
      - "465:465"
      - "587:587"
      - "993:993"
      - "995:995"
      - "4190:4190"
    volumes:
      - /dockerdata/posteio:/data
      - /etc/localtime:/etc/localtime:ro

  nginx:
    image: wonderfall/boring-nginx
    container_name: nginx
    links:
      - mailserver:mailserver
      - discourse:discourse
      - ghost:ghost
    ports:
      - "80:8000"
      - "443:4430"
    volumes:
      - /dockerdata/nginx/sites-enabled:/sites-enabled
      - /dockerdata/nginx/conf:/conf.d
      - /dockerdata/nginx/log:/var/log/nginx
      - /dockerdata/nginx/certs:/certs
    depends_on:
      - mailserver
      - discourse

  postgresql:
    image: bitnami/postgresql:latest
    container_name: postgresql
    volumes:
      - /dockerdata/postgresql:/bitnami

  redis:
    image: bitnami/redis:latest
    container_name: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - /dockerdata/redis:/bitnami

  discourse:
    image: bitnami/discourse:latest
    container_name: discourse
    volumes:
      - /dockerdata/discourse:/bitnami
    depends_on:
      - postgresql
      - redis

  sidekiq:
    image: bitnami/discourse:latest
    container_name: sidekiq
    depends_on:
      - discourse
    volumes:
      - /dockerdata/sidekiq:/bitnami
    command: 'nami start --foreground discourse-sidekiq'

  ghost:
    image: bitnami/ghost:latest
    container_name: ghost
    labels:
      kompose.service.type: nodeport
    volumes:
      - /dockerdata/ghost:/bitnami
    depends_on:
      - mariadb
    environment:
      - GHOST_HOST=www.tek-machina.com
      - GHOST_USERNAME=Malfurious
      - GHOST_PASSWORD=w4H3nVBw2plGxj3ieklM
      - BLOG_TITLE='Tek-Machina'

  mariadb:
    image: bitnami/mariadb:latest
    container_name: mariadb
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - /dockerdata/mariadb:/bitnami

