version: '2'
services:
  mailserver:
    image: hardware/mailserver
    container_name: mailserver
    domainname: othala.us                
    hostname: mail
    ports:
      - "25:25"     # SMTP                - Required
      - "143:143"   # IMAP       STARTTLS - Optional - For webmails/desktop clients
      - "587:587"   # Submission STARTTLS - Optional - For webmails/desktop clients
      - "993:993"   # IMAPS      SSL/TLS  - Optional - For webmails/desktop clients
      - "4190:4190" # SIEVE      STARTTLS - Optional - Recommended for mail filtering
    environment:
      - DBPASS=postfix
    volumes:
      - /mnt/docker/mail:/var/mail
      - /mnt/docker/mail/opendkim:/etc/opendkim/keys
      - /mnt/docker/nginx/certs:/etc/letsencrypt
    depends_on:
      - mariadb

  postfixadmin:
    image: hardware/postfixadmin
    container_name: postfixadmin
    domainname: othala.us
    hostname: mail
    environment:
      - DBPASS=postfix
    depends_on:
      - mailserver
      - mariadb

  rainloop:
    image: hardware/rainloop
    container_name: rainloop
    volumes:
      - /mnt/docker/rainloop:/rainloop/data
    depends_on:
      - mailserver
      - mariadb

  nginx:
    image: wonderfall/boring-nginx
    container_name: nginx
    ports:
      - "80:8000"
      - "443:4430"
    volumes:
      - /mnt/docker/nginx/sites-enabled:/sites-enabled
      - /mnt/docker/nginx/conf:/conf.d
      - /mnt/docker/nginx/log:/var/log/nginx
      - /mnt/docker/nginx/certs:/certs
    depends_on:
      - postfixadmin
      - rainloop

  mariadb:
    image: mariadb:10.1
    container_name: mariadb
    # restart: always
    # Info : These variables are ignored when the volume already exists (databases created before).
    environment:
      - MYSQL_ROOT_PASSWORD=xXtYcbJ57ise9vp7jT0j
      - MYSQL_DATABASE=postfix
      - MYSQL_USER=postfix
      - MYSQL_PASSWORD=postfix
    volumes:
      - /mnt/docker/mysql/db:/var/lib/mysql