version: '2'
services:
  mailserver:
    image: hardware/mailserver
    container_name: mailserver
    domainname: othala.us                
    hostname: mail
      restart: always
      extra_hosts:                        - Required for external database (on other server or for local database on host)
       - "mariadb:192.168.1.2"            - Replace with IP address of MariaDB server
    ports:
      - "25:25"     # SMTP                - Required
      - "143:143"   # IMAP       STARTTLS - Optional - For webmails/desktop clients
      - "587:587"   # Submission STARTTLS - Optional - For webmails/desktop clients
      - "993:993"   # IMAPS      SSL/TLS  - Optional - For webmails/desktop clients
      - "4190:4190" # SIEVE      STARTTLS - Optional - Recommended for mail filtering
    environment:
      - DBPASS=postfix
    volumes:
      - /mnt/docker/mail:/var/mail
      - /mnt/docker/mail/opendkim:/etc/opendkim/keys
      - /mnt/docker/nginx/certs:/etc/letsencrypt
    depends_on:
      - mariadb

  postfixadmin:
    image: hardware/postfixadmin
    container_name: postfixadmin
    domainname: othala.us
    hostname: mail
      restart: always
    environment:
      - DBPASS=postfix
    depends_on:
      - mailserver
      - mariadb

  rainloop:
    image: hardware/rainloop
    container_name: rainloop
      restart: always
    volumes:
      - /mnt/docker/rainloop:/rainloop/data
    depends_on:
      - mailserver
      - mariadb

  nginx:
    image: wonderfall/boring-nginx
    container_name: nginx
      restart: always
    ports:
      - "80:8000"
      - "443:4430"
    volumes:
      - /mnt/docker/nginx/sites-enabled:/sites-enabled
      - /mnt/docker/nginx/conf:/conf.d
      - /mnt/docker/nginx/log:/var/log/nginx
      - /mnt/docker/nginx/certs:/certs
    depends_on:
      - postfixadmin
      - rainloop

