version: '2.1'

services:
  mailserver:
    image: hardware/mailserver
    container_name: mailserver
    domainname: tek-machina.com                 # Mail server A/MX/FQDN & reverse PTR = mail.domain.tld.
    hostname: mail
    # restart: always
    # extra_hosts:                          - Required for external database (on other server or for local databases on host without docker)
    #  - "mariadb:xx.xx.xx.xx"              - Replace with IP address of MariaDB server
    #  - "redis:xx.xx.xx.xx"                - Replace with IP address of Redis server
    ports:
      - "25:25"       # SMTP                - Required
    # - "110:110"     # POP3       STARTTLS - Optional - For webmails/desktop clients
      - "143:143"     # IMAP       STARTTLS - Optional - For webmails/desktop clients
    # - "465:465"     # SMTPS      SSL/TLS  - Optional - Enabled for compatibility reason, otherwise disabled
      - "587:587"     # Submission STARTTLS - Optional - For webmails/desktop clients
      - "993:993"     # IMAPS      SSL/TLS  - Optional - For webmails/desktop clients
    # - "995:995"     # POP3S      SSL/TLS  - Optional - For webmails/desktop clients
      - "4190:4190"   # SIEVE      STARTTLS - Optional - Recommended for mail filtering
    environment:
      - DBPASS=fKWOlIAHx4qP5sDj6Wwi                      # MariaDB database password (required)
      - RSPAMD_PASSWORD=bENxrcJCS21jbuaC5dQE             # Rspamd WebUI password (required)
      - ADD_DOMAINS=postfix.tek-machina.com,webmail.tek-machina.com,spam.tek-machina.com,forum.tek-machina.com,wiki.tek-machina.com,www.tek-machina.com   # Add additional domains separated by commas (needed for dkim keys etc.)
    # - ENABLE_POP3=true                    # Enable POP3 protocol
    # - ENABLE_FETCHMAIL=true               # Enable fetchmail forwarding
    # - DISABLE_CLAMAV=true                 # Disable virus scanning
    # - DISABLE_SIGNING=true                # Disable DKIM/ARC signing
    # - DISABLE_GREYLISTING=true            # Disable greylisting policy
    # - DISABLE_RATELIMITING=true           # Disable ratelimiting policy
    #
    # Full list : https://github.com/hardware/mailserver#environment-variables
    #
    volumes:
      - /DockerData/Mail:/var/mail
      - /DockerData/Nginx/certs:/etc/letsencrypt
    depends_on:
      - mariadb
      - redis

  # Administration interface
  postfixadmin:
    image: hardware/postfixadmin
    container_name: postfixadmin
    domainname: tek-machina.com
    hostname: mail
    # restart: always
    environment:
      - DBPASS=fKWOlIAHx4qP5sDj6Wwi
    depends_on:
      - mailserver
      - mariadb

  # Webmail (Optional)
  rainloop:
    image: hardware/rainloop
    container_name: rainloop
    # restart: always
    volumes:
      - /DockerData/Rainloop:/rainloop/data
    depends_on:
      - mailserver
      - mariadb

  # Web server
  nginx:
    image: wonderfall/boring-nginx
    container_name: nginx
    # restart: always
    ports:
      - "80:8000"
      - "443:4430"
    volumes:
      - /DockerData/Nginx/sites-enabled:/sites-enabled
      - /DockerData/Nginx/conf:/conf.d
      - /DockerData/Nginx/log:/var/log/nginx
      - /DockerData/Nginx/certs:/certs
    depends_on:
      - mailserver
      - postfixadmin
      - rainloop

  # Database
  mariadb:
    image: mariadb:10.1
    container_name: mariadb
    # restart: always
    # Info : These variables are ignored when the volume already exists (databases created before).
    environment:
      - MYSQL_ROOT_PASSWORD=RsCNFqReU5OeE3r9yGMe
      - MYSQL_DATABASE=postfix
      - MYSQL_USER=postfix
      - MYSQL_PASSWORD=fKWOlIAHx4qP5sDj6Wwi
    volumes:
      - /DockerData/Mariadb:/var/lib/mysql

  # Cache Database
  redis:
    image: redis:3.2-alpine
    container_name: redis
    # restart: always
    command: redis-server --appendonly yes
    sysctls:
      - net.core.somaxconn=1024
    volumes:
      - /DockerData/Redis:/data
